/* ============================================================================
   GROK BOT GALAXY LIVE — SCREENS DATA
   ----------------------------------------------------------------------------
   Key frames captured from the Days 1–3 replays, shown in the SCREENS gallery
   linked from PRODUCT feature evidence. Served from ./screens/<file>.

   window.GG_SCREENS = [{
     id      : unique slug
     file    : "screens/<name>.png"
     t       : replay position (hh:mm:ss) — "find it in the replay" pointer
     wall    : approximate Pacific wall time
     title   : short title
     caption : what the viewer is looking at, 1–2 sentences
     feature : optional — feature id in products.js this screen belongs to
     kind    : "product" | "session" | "build" | "stage"
   }]
   ============================================================================ */

window.GG_SCREENS = [
  { id: "opening-trio", file: "screens/opening-trio.png", t: "00:00:56", wall: "9:07 AM", title: "The trio opens the day", caption: "Lauren, Roshan and Matt sit at the build table as the stream begins, with no idea chosen yet.", kind: "stage" },
  { id: "onboarding", file: "screens/onboarding.png", t: "00:41:32", wall: "9:48 AM", title: "Creating your first bot", caption: "Grok Bot 101 walks a new user through picking a job category — data & analysis, research & figures, workflows & routines — after which the bot is named and scoped for you.", kind: "session", feature: null },
  { id: "marketplace", file: "screens/marketplace.png", t: "01:01:19", wall: "10:08 AM", title: "The bot Marketplace", caption: "Community-built bots carry creator bylines and install buttons ('Lenny's APIs', 'Diana's Tips') — the app-store surface for agents.", kind: "session", feature: null },
  { id: "email-demo", file: "screens/email-demo.png", t: "01:21:06", wall: "10:28 AM", title: "Email negotiation, handled", caption: "A supplier email about a 500-unit winter shipment sits in the inbox while the bot drafts the confirmation and a logistics memo beside it.", kind: "session" },
  { id: "business-plan", file: "screens/business-plan.png", t: "02:00:40", wall: "11:07 AM", title: "The business-plan prompt", caption: "A full plan is requested in one line — product, pricing tiers, marketing strategy, objectives — and comes back with a scoping checklist across marketing, sales, ops, finance and legal.", kind: "build" },
  { id: "idea-thread", file: "screens/idea-thread.png", t: "02:21:21", wall: "11:28 AM", title: "Where 'Pop-up OS' was chosen", caption: "In the idea-selection thread, humans rejected the first directions and agents came back with candidates — food company, high-ticket sales, event-book, ticket-craft — before the restaurant pop-up won.", kind: "build" },
  { id: "cody-guest", file: "screens/cody-guest.png", t: "02:18:30", wall: "11:25 AM", title: "Codie Sanchez on distribution", caption: "The guest segment set the day's go-to-market doctrine: sell to three people first, distribution is the moat, controversy marketing, keep a proof vault.", kind: "session" },
  { id: "eng-keynote", file: "screens/eng-keynote.png", t: "04:00:15", wall: "1:07 PM", title: "Introducing Grok Bot: the integration stack", caption: "The keynote presents fully autonomous agents with GitHub, Notion, Figma and Slack connections, first-party Cursor Cloud Agents management, and memory and routines.", kind: "session", feature: "agent-pipeline" },
  { id: "eng-debug", file: "screens/eng-debug.png", t: "04:59:36", wall: "2:06 PM", title: "Debugging a stuck cloud agent, live", caption: "steve diagnoses an agent 'still chasing the PR, not the spinner'; tater posts PR #10 to for-review via cursor.com/agents. The product spec line — events with date/time, sessions, venue, staff — is visible in this thread.", kind: "build", feature: "agent-pipeline" },
  { id: "pm-chat", file: "screens/pm-chat.png", t: "05:58:00", wall: "3:00 PM", title: "PM session: the 'Bot team' chat", caption: "The management demo — an analyst agent answering with linked data and an RFC — ran on sample venue data (cabins and glider flights), not the trio's restaurant build.", kind: "session" },
  { id: "fleet-26", file: "screens/fleet-26.png", t: "06:48:00", wall: "3:55 PM", title: "The fleet dashboard: 26 bots, 10 already retired", caption: "The org's pulse in one widget doubles as proof the fleet churns staff, with ten bots already retired by mid-afternoon.", kind: "build", feature: "fleet-widget" },
  { id: "price-menu", file: "screens/price-menu.png", t: "07:07:00", wall: "4:14 PM", title: "Price menu with web-sourced imagery", caption: "An agent assembles a tiered price menu from web reference images and ends with the human-in-the-loop question: 'Which one do you like?'", kind: "build", feature: "activities-menu" },
  { id: "signup-staging", file: "screens/signup-staging.png", t: "07:13:00", wall: "4:20 PM", title: "The sign-up page — live on Vercel, pre-launch", caption: "Eighteen minutes after the wireframe board went up, a booking sign-up flow (name, email, password, ZIP) was running in a preview browser. The domain (shipbythursday.day) went live on Vercel wired to PlanetScale — and the hosts told viewers 'don't submit yet… throwaway prototype.'", kind: "build", feature: "booking-signup" },
  { id: "tickets-plush", file: "screens/tickets-plush.png", t: "07:14:00", wall: "4:21 PM", title: "Night-market ticket stubs and Grok Bot plush concepts", caption: "The pop-up's physical kit gets designed live — CSS ticket stubs with tier badges, plus plush characters checked 'against the official art' and iterated.", kind: "build", feature: "ticket-badge" },
  { id: "teebot-email", file: "screens/teebot-email.png", t: "07:21:00", wall: "4:28 PM", title: "Tee Bot opens the email channel", caption: "Tee Bot drafts promo emails for the merch line with best-seller banners in and generic roundup formats deliberately left out.", kind: "build", feature: "email-channel" },
  { id: "maturity-curve", file: "screens/maturity-curve.png", t: "07:26:00", wall: "4:33 PM", title: "The AI Maturity Curve", caption: "The keynote's framing chart climbs from asking (chatbots) to doing a task (copilots), then to automating a job (a bot), and tops out at staffing a function (a team of bots). xAI's product sits on the top rung.", kind: "session" },
  { id: "why-grokbot", file: "screens/why-grokbot.png", t: "07:30:00", wall: "4:37 PM", title: "'Why Grok Bot': the five pillars", caption: "The five pillars are easy as iMessage, always-on 24/7, using your tools like you (computer use with your logins), finishing the work, and shareable templates.", kind: "session" },
  { id: "optimizing-costs", file: "screens/optimizing-costs.png", t: "07:43:00", wall: "4:50 PM", title: "Optimizing Costs — with 1M views watching", caption: "The honesty slide shows what browser-using agents actually cost to run, displayed while the broadcast crossed one million views.", kind: "session" },
  { id: "seo-workorder", file: "screens/seo-workorder.png", t: "07:48:00", wall: "4:55 PM", title: "The SEO work order", caption: "A bot-written growth plan with keyword targets, page fixes and a dated execution timeline arrives as a work order, not a report.", kind: "build", feature: "seo-work-order" },
  { id: "closing-guest", file: "screens/closing-guest.png", t: "08:17:00", wall: "5:24 PM", title: "Closing guest interview", caption: "The day's final segment brings a remote guest together with the build trio before the stream closed at 1.1M views.", kind: "stage" },

  /* ── Day 2 — Wed Sep 16 ── */
  { id: "d2-opening", file: "screens/d2-opening.png", t: "00:00:15 (Day 2 replay)", wall: "8:30 AM", day: 2, title: "Day 2 hold screen — the sales track begins", caption: "In a new broadcast from the same studio, the fleet's second day opens with the question of the day — can it sell what it built?", kind: "stage" },
  { id: "d2-se-usecases", file: "screens/d2-whiteboard.png", t: "00:40:00 (Day 2 replay)", wall: "9:10 AM", day: 2, title: "Four ways bots can help a sales engineer", caption: "The SE session's slide introduces four helpers — an Engineer that drafts a technical resource in seconds, a Customer Expert that knows Codebricks and PlayerScale and flags unusual usage and power users, Echo, which updates the deck live during calls with Granola and Gong follow-up, and Competitive Intel, which uses competitor products to keep battlecards current.", kind: "session" },
  { id: "d2-vision-deck", file: "screens/d2-vision-deck.png", t: "00:59:00 (Day 2 replay)", wall: "9:29 AM", day: 2, title: "Amrita's vision deck, assembled on screen", caption: "A Google Slides window titled as Amrita's vision deck, on screen during the Sales Engineering session. Her point about bot-built decks, made on air, was that it cost her $20–30 versus four or five hours by hand.", kind: "session" },
  { id: "d2-se-bots", file: "screens/d2-se-bots.png", t: "01:03:00 (Day 2 replay)", wall: "9:33 AM", day: 2, title: "Two bots work one customer request together", caption: "In the Sales Engineering session's demo chat, two agents trade messages to move a customer request forward, each doing its half of the job.", kind: "session" },
  { id: "d2-prototype", file: "screens/d2-prototype.png", t: "01:35:00 (Day 2 replay)", wall: "10:05 AM", day: 2, title: "The first playable draft: 'NodeBots BTB'", caption: "Two rows of three drafted bots face off, each card carrying its rarity tier, with a WIN stamp and a replay button below the board — the build the fleet shipped under the code name 'Cupcake'.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-game-docs", file: "screens/d2-game-docs.png", t: "01:50:00 (Day 2 replay)", wall: "10:20 AM", day: 2, title: "The game documentation, written down", caption: "The design lands in Notion: rosters, matches and replays, an Elo rating that starts every account at 1000, and the rarity draw from 90% common down to 0.9% epic.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-battle-whiteboard", file: "screens/d2-battle-whiteboard.png", t: "03:13:00 (Day 2 replay)", wall: "11:43 AM", day: 2, title: "Matchup screens, wireframed live", caption: "The matchup flow takes shape on the shared drawing canvas — a player's card wired to Dr. Eggbot on one side and a random draw on the other.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-design-brief", file: "screens/d2-design-brief.png", t: "03:27:00 (Day 2 replay)", wall: "11:57 AM", day: 2, title: "The Chief of Staff drafts the design brief", caption: "One of the specialist bots writes the game's design brief in the workspace while the build continues around it.", kind: "build" },
  { id: "d2-bot-workspace", file: "screens/d2-bot-workspace.png", t: "03:34:00 (Day 2 replay)", wall: "12:04 PM", day: 2, title: "Choosing an animation framework, delegated", caption: "The Chief of Staff surveys front-end animation options and reports back — one of several bot tasks running in parallel at midday.", kind: "build" },
  { id: "d2-echo", file: "screens/d2-echo.png", t: "03:50:00 (Day 2 replay)", wall: "12:20 PM", day: 2, title: "Echo tries its voice lines", caption: "Echo, an announcer bot for the game, tests its play-by-play lines in the chat.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-team-builder", file: "screens/d2-team-builder.png", t: "03:54:00 (Day 2 replay)", wall: "12:24 PM", day: 2, title: "The team builder, working", caption: "Pick a captain, reroll or confirm the roster — and the account bar already reads a Diamond rating of 1585.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-ads", file: "screens/d2-ads.png", t: "05:40:00 (Day 2 replay)", wall: "2:10 PM", day: 2, title: "The ad copy pass", caption: "The marketing bot drafts numbered ad and landing-page copy for the launch push.", kind: "build", feature: "ads-pipeline" },
  { id: "d2-offer", file: "screens/d2-offer.png", t: "07:30:00 (Day 2 replay)", wall: "4:00 PM", day: 2, title: "The on-stream offer", caption: "The event's own promo slide offered a free month of Grok Bot to the first 1,000 users who duplicate Dr. Eggbot's template, QR code and all.", kind: "stage" },
  { id: "d2-close", file: "screens/d2-close.png", t: "08:22:30 (Day 2 replay)", wall: "4:52 PM", day: 2, title: "Day 2 signs off", caption: "The closing slate sets up the finale: 'Final day starts tomorrow at 8:30am PST.' The broadcast ended at 4:53 PM PT at 374.9K views.", kind: "stage" },

  /* ── Day 3 — Thu Sep 17 ── */
  { id: "d3-revops-usecases", file: "screens/d3-revops-usecases.png", t: "00:37:30 (Day 3 replay)", wall: "9:07 AM", day: 3, title: "Six ways bots help marketing teams, on one slide", caption: "Marketing Operations opened on six plays: a self-completing to-do list, tools not just rules, the marketing–sales handoff, self-serve GTM data, territory planning, and a one-time CRM cleanup.", kind: "session" },
  { id: "d3-territory-planner", file: "screens/d3-territory-planner.png", t: "00:40:00 (Day 3 replay)", wall: "9:10 AM", day: 3, title: "Territory Planner referees an account dispute", caption: "A 'Territory Planner' bot drafted the stakeholder email and filed a Path task: two AEs claimed the same account; a territory-map sync Tuesday and a written ruling by Friday — with Approve / Hold buttons waiting on a human.", kind: "session" },
  { id: "d3-juno-lead-app", file: "screens/d3-juno-lead-app.png", t: "00:45:00 (Day 3 replay)", wall: "9:15 AM", day: 3, title: "Juno turns one line into a lead-review app spec", caption: "'A GTM product bot' named Juno took 'build an internal app for sales reps to review leads' and specced a swipe interface — left rejects with a reason, right accepts into a follow-up sequence — flagging auth as a day-one requirement.", kind: "session" },
  { id: "d3-starbase-contest", file: "screens/d3-starbase-contest.png", t: "01:10:00 (Day 3 replay)", wall: "9:40 AM", day: 3, title: "The Starbase challenge, step by step", caption: "The viewer contest slide asks entrants to quote the challenge post, explain what their Bot does, link their shared Bot template, and follow @Grok and @Bot — the prize is a trip to Starbase, with entries through Sept 29.", kind: "stage" },
  { id: "d3-sake-game-stats", file: "screens/d3-sake-game-stats.png", t: "02:10:00 (Day 3 replay)", wall: "10:40 AM", day: 3, title: "A stats bot reads live match data", caption: "The studio block's build screen shows a 'Launch dashboard — Session 1' card with a bug list (two fixed, two open), while Sake, a stats bot, pulls win-rate and difficulty signals from live match data to validate the game engine. The day's agenda sits beside it with build blocks around Grok Bot for Customer Success and Grok Bot for Marketing.", kind: "build" },
  { id: "d3-integrations", file: "screens/d3-integrations.png", t: "02:16:00 (Day 3 replay)", wall: "10:46 AM", day: 3, title: "The integrations bot reports everything it connected", caption: "An 'Integrations' bot reports the connections in one message — GitHub with two repos, Slack with three channels, Notion with four databases, Linear with two projects, Vercel and Postgres, plus webhooks — and closes with a 'sudden-death feature kill-list' for the ship cut-line, signed 'Ship by Thursday.'", kind: "build" },
  { id: "d3-round1", file: "screens/d3-round1.png", t: "02:22:00 (Day 3 replay)", wall: "10:52 AM", day: 3, title: "'You took round 1' — the first live match of Day 3", caption: "The game demo's match-result screen shows a Play Again button, with team cards carrying the charisma-vs-dexterity bars, several still reading 'no image provided' while an Image Gen bot sits active in the roster.", kind: "build" },
  { id: "d3-match-pets", file: "screens/d3-match-pets.png", t: "02:23:00 (Day 3 replay)", wall: "10:52 AM", day: 3, title: "Inside a live match: player pets and a roll of the dice", caption: "The in-match view shows player pets on the cards (a capybara and a galago among them), a dice-roll RNG mechanic between the teams, and a five-round format with the round-1 win lit up.", kind: "build" },
  { id: "d3-thursday-arena", file: "screens/d3-thursday-arena.png", t: "02:28:00 (Day 3 replay)", wall: "10:58 AM", day: 3, title: "Thursday Arena goes live on a deployed front page", caption: "The rename-and-deploy promise was kept with a matchmaking front page carrying a player profile at a 1000 rating, a Play button, a 'priority queue: eng' banner, and Leaderboard / Your matches / Tips / Read handbook panels, beside a deploy diff in the editor.", kind: "build", feature: "thursday-lander" },
  { id: "d3-arena-leaderboard", file: "screens/d3-arena-leaderboard.png", t: "02:29:00 (Day 3 replay)", wall: "10:58 AM", day: 3, title: "The Thursday Arena leaderboard, live", caption: "Named players with win-loss records and Elo ratings fill the leaderboard the hosts wired up on Day 2, now carrying real matches.", kind: "build", feature: "auth-backend" },
  { id: "d3-shop", file: "screens/d3-shop.png", t: "02:49:00 (Day 3 replay)", wall: "11:19 AM", day: 3, title: "The shop's items are jokes about the sales world", caption: "Thursday Arena grows a shop with three cards on the shelf, each priced at 3G — including one whose sales pitch is a wink at go-to-market culture: a hiring-signals tracker that 'snipes the hire you just missed.'", kind: "build" },
  { id: "d3-analytics", file: "screens/d3-analytics.png", t: "03:00:00 (Day 3 replay)", wall: "11:30 AM", day: 3, title: "Thursday Arena's analytics dashboard", caption: "The game's own dashboard reads 2,255 practice sessions and 2,983 matches so far, with signups, D1/D3/D7 retention bars, and top-converting countries led by the US at 45.8%.", kind: "build", feature: "cupcake-prototype" },
  { id: "d3-marketplace-cs", file: "screens/d3-marketplace-cs.png", t: "04:08:00 (Day 3 replay)", wall: "12:38 PM", day: 3, title: "The Post-Sales session shops the Marketplace", caption: "Featured community bots (dr.eggbot, Lenny Rachitsky's Overheard, Claire Vo's Tradbot) beside team plugins — Atlassian MCP, GitHub, the Flylo demo environment — as the session assembles a post-sales team from installed specialists.", kind: "session" },
  { id: "d3-gus-digest", file: "screens/d3-gus-digest.png", t: "04:21:00 (Day 3 replay)", wall: "12:51 PM", day: 3, title: "Gus files the post-sales digest", caption: "Gus, a chief-of-staff bot, files a status brief for Flylo's demo post-sales team covering Risk, People, Blockers and Open promises, with its routines listed beside it — a daily brief, call prep every 15 minutes, weekly unattended-promises sweeps, ask watch and visibility watch.", kind: "session" },
  { id: "d3-self-improvement", file: "screens/d3-self-improvement.png", t: "04:28:00 (Day 3 replay)", wall: "12:58 PM", day: 3, title: "The self-improvement scan", caption: "A weekly routine audits its own routines and proposes one fix ('don't implement unless I say yes'), then diffs its drafted messages against the ones the manager actually sent — tone, closings, banned phrases — logging the deltas as memory.", kind: "session" },
  { id: "d3-thursdayarena-live", file: "screens/d3-thursdayarena-live.png", t: "04:49:00 (Day 3 replay)", wall: "1:19 PM", day: 3, title: "thursdayarena.com — the URL on screen", caption: "The address bar reads thursdayarena.com over the deployed landing page: the THURSDAY ARENA wordmark with its cupcake pixel-art mascot, a Play button, and the roster's character cards fanned out beside it.", kind: "build", feature: "thursday-lander" },
  { id: "d3-arena-x-ticker", file: "screens/d3-arena-x-ticker.png", t: "05:36:00 (Day 3 replay)", wall: "2:06 PM", day: 3, title: "The landing page runs a ticker of player posts", caption: "The deployed site carried the THURSDAY ARENA wordmark and its cupcake mascot over Play and Practice buttons, with character cards for Mushroom Ninja, Poisonous Potato and Flamingo fanned below — and under them a live ticker of X posts scrolling past, where players were posting the teams they built ('played on my lunch break') as the view counter read 134.9K.", kind: "product", feature: "cupcake-prototype" },
  { id: "d3-closing-agenda", file: "screens/d3-closing-agenda.png", t: "05:59:00 (Day 3 replay)", wall: "2:29 PM", day: 3, title: "The final showcase is set for 3:15 PM", caption: "The stream's agenda board lays out the closing run — the Marketing session, one more game-studio build block at 2:45, then 'Livestream Wrap and Final Showcase' at 3:15 PM PT. The studio table sat mid-conversation as the board went up, at 141.3K views.", kind: "stage" },
  { id: "d3-market-researcher", file: "screens/d3-market-researcher.png", t: "06:06:00 (Day 3 replay)", wall: "2:36 PM", day: 3, title: "The Market Researcher bot takes its one-message brief", caption: "Josh Kim opened the final Marketing session by briefing a 'Market Researcher' bot in a single message — research the product by reading its own website, understand the market, then deeply map three competitors and where to position against them — with a sidebar fleet of Market Eval, Product Marketer, performance and strategy bots waiting behind it.", kind: "session" },
  { id: "d3-website-ops", file: "screens/d3-website-ops.png", t: "06:18:00 (Day 3 replay)", wall: "2:48 PM", day: 3, title: "A marketing bot takes a three-step order", caption: "In the Marketing session's demo, a 'Website Ops' bot is told to build the landing page from the Product Marketer's brief, update the FAQs, and send screenshots as it goes — and it replies that it is pulling the brief and opening a PR with progress shots.", kind: "session" },
  { id: "d3-marketing-lessons", file: "screens/d3-marketing-lessons.png", t: "06:33:00 (Day 3 replay)", wall: "3:03 PM", day: 3, title: "The Marketing session closes on three lessons", caption: "The session's 'What we learned' slide ran three boxes: scope bots like a job description, then trust them with the tools, access and context a teammate would get, then invest in them the way you would a person — and copy the marketplace's shared templates, QR code included — as the view counter read 149K.", kind: "session" },
  { id: "d3-finale-numbers", file: "screens/d3-finale-numbers.png", t: "06:46:00 (Day 3 replay)", wall: "3:16 PM", day: 3, title: "The final showcase opens on the game's live numbers", caption: "The closing segment opens on the game's metrics dashboard, which reads 4,898 public matches (up from 2,983 at 11:30 AM), 4,500 practice sessions, 1,650 X logins at an 8.0% conversion, a 47.6% public win rate, and 332 feedback items, with four at the studio table to walk through them.", kind: "stage" },
  { id: "d3-live-vs-viewer", file: "screens/d3-live-vs-viewer.png", t: "07:08:00 (Day 3 replay)", wall: "3:38 PM", day: 3, title: "The hosts take a ranked match against a viewer", caption: "The showcase match put the studio's players on the public site against @maxnewworld, the scoreboard at 0–0 in the opening round with rating figures riding on the outcome and the bot BATTLING BEBOP in play, at 156.7K views.", kind: "product", feature: "cupcake-prototype" },
  { id: "d3-677-playing", file: "screens/d3-677-playing.png", t: "07:11:00 (Day 3 replay)", wall: "3:41 PM", day: 3, title: "Six hundred and seventy-seven people are playing as the hosts face a viewer", caption: "Mid-match in the showcase, the hosts are up 1-0 on the viewer @maxnewworld in a best-of-three with an opponent's card on the table, and the public site's banner reads 677 people playing now.", kind: "product", feature: "cupcake-prototype" },
  { id: "d3-official-rules", file: "screens/d3-official-rules.png", t: "07:42:00 (Day 3 replay)", wall: "4:12 PM", day: 3, title: "dr. eggbot states the official rules in the coaching chat", caption: "The hosts played their last match with the rules on screen beside them: a match is best-of-3, each round running a shop phase followed by an auto battle; ten tokens arrive every round and unspent ones vanish; bots and the apple persist between rounds while the potato is temporary. The view counter read 168.8K.", kind: "product", feature: "cupcake-prototype" },
  { id: "d3-traffic-chart", file: "screens/d3-traffic-chart.png", t: "07:45:00 (Day 3 replay)", wall: "4:15 PM", day: 3, title: "The day's traffic arrives in five-minute waves", caption: "The showcase's traffic chart, stamped 4:15 PM PT: practice starts and X signups rising in waves across the whole broadcast day, each wave traceable to something the stream had just done on air, at 171.4K views.", kind: "product", feature: "cupcake-prototype" },
  { id: "d3-day3-close", file: "screens/d3-day3-close.png", t: "07:58:20 (Day 3 replay)", wall: "4:28 PM", day: 3, title: "Day 3 signs off with the deadline met", caption: "The broadcast's final card — 'Thanks for joining!' — came after 7h 58m on air, closing at 173.4K views with the fleet's last reading showing 43 bots and 76 milestones logged. The company shipped Thursday Arena on the day it promised.", kind: "stage" }
];
