/* ============================================================================
   GROK BOT GALAXY LIVE — SCREENS DATA
   ----------------------------------------------------------------------------
   Key frames captured from the Days 1–3 replays, shown in the SCREENS gallery
   linked from PRODUCT feature evidence. Served from ./screens/<file>.

   window.GG_SCREENS = [{
     id      : unique slug
     file    : "screens/<name>.png"
     t       : replay position (hh:mm:ss) — "find it in the replay" pointer
     wall    : approximate Pacific wall time
     title   : short title
     caption : what the viewer is looking at, 1–2 sentences
     feature : optional — feature id in products.js this screen belongs to
     kind    : "product" | "session" | "build" | "stage"
   }]
   ============================================================================ */

window.GG_SCREENS = [
  { id: "opening-trio", file: "screens/opening-trio.png", t: "00:00:56", wall: "9:07 AM", title: "The trio opens the day", caption: "Lauren, Roshan and Matt at the build table as the stream begins — no idea chosen yet.", kind: "stage" },
  { id: "onboarding", file: "screens/onboarding.png", t: "00:41:32", wall: "9:48 AM", title: "Creating your first bot", caption: "Grok Bot 101's onboarding: pick a job category — data & analysis, research & figures, workflows & routines — and the bot is named and scoped for you.", kind: "session", feature: null },
  { id: "marketplace", file: "screens/marketplace.png", t: "01:01:19", wall: "10:08 AM", title: "The bot Marketplace", caption: "Community-built bots with creator bylines and install buttons ('Lenny's APIs', 'Diana's Tips') — the app-store surface for agents.", kind: "session", feature: null },
  { id: "email-demo", file: "screens/email-demo.png", t: "01:21:06", wall: "10:28 AM", title: "Email negotiation, handled", caption: "A supplier email about a 500-unit winter shipment, with the bot drafting the confirmation and a logistics memo beside it.", kind: "session" },
  { id: "business-plan", file: "screens/business-plan.png", t: "02:00:40", wall: "11:07 AM", title: "The business-plan prompt", caption: "A full plan requested in one line — product, pricing tiers, marketing strategy, objectives — with a scoping checklist across marketing, sales, ops, finance and legal.", kind: "build" },
  { id: "idea-thread", file: "screens/idea-thread.png", t: "02:21:21", wall: "11:28 AM", title: "Where 'Pop-up OS' was chosen", caption: "The idea-selection thread: humans rejected the first directions, agents came back with candidates — food company, high-ticket sales, event-book, ticket-craft — and the restaurant pop-up won.", kind: "build" },
  { id: "cody-guest", file: "screens/cody-guest.png", t: "02:55:00", wall: "11:25 AM", title: "Codie Sanchez on distribution", caption: "The guest segment that set the go-to-market doctrine: sell to three people first, distribution is the moat, controversy marketing, keep a proof vault.", kind: "session" },
  { id: "eng-keynote", file: "screens/eng-keynote.png", t: "04:00:15", wall: "1:07 PM", title: "Introducing Grok Bot: the integration stack", caption: "Fully autonomous agents; GitHub, Notion, Figma and Slack connections; first-party Cursor Cloud Agents management; memory and routines.", kind: "session", feature: "agent-pipeline" },
  { id: "eng-debug", file: "screens/eng-debug.png", t: "04:59:36", wall: "2:06 PM", title: "Debugging a stuck cloud agent, live", caption: "steve diagnoses an agent 'still chasing the PR, not the spinner'; tater posts PR #10 to for-review via cursor.com/agents. The product spec line — events with date/time, sessions, venue, staff — is visible in this thread.", kind: "build", feature: "agent-pipeline" },
  { id: "pm-chat", file: "screens/pm-chat.png", t: "05:58:00", wall: "3:00 PM", title: "PM session: the 'Bot team' chat", caption: "The management demo — an analyst agent answering with linked data and an RFC — ran on sample venue data (cabins and glider flights), not the trio's restaurant build.", kind: "session" },
  { id: "fleet-26", file: "screens/fleet-26.png", t: "04:48:00", wall: "3:55 PM", title: "Fleet widget: 26 bots, 880 requests, 10 archived", caption: "The org's pulse in one widget — and proof the fleet churns staff: ten bots already retired by mid-afternoon.", kind: "build", feature: "fleet-widget" },
  { id: "price-menu", file: "screens/price-menu.png", t: "05:07:00", wall: "4:14 PM", title: "Price menu with web-sourced imagery", caption: "An agent assembling a tiered price menu from web reference images, ending with the human-in-the-loop question: 'Which one do you like?'", kind: "build", feature: "activities-menu" },
  { id: "signup-staging", file: "screens/signup-staging.png", t: "05:13:00", wall: "4:20 PM", title: "The sign-up page — live on Vercel, pre-launch", caption: "Roughly forty-five minutes after the first wireframe, a booking sign-up flow (name, email, password, ZIP) in a preview browser. The domain (shipbythursday.day) went live on Vercel wired to PlanetScale — and the hosts told viewers 'don't submit yet… throwaway prototype.'", kind: "build", feature: "booking-signup" },
  { id: "tickets-plush", file: "screens/tickets-plush.png", t: "05:14:00", wall: "4:21 PM", title: "Night-market ticket stubs and Grok Bot plush concepts", caption: "The pop-up's physical kit designed live: CSS ticket stubs with tier badges, and plush characters checked 'against the official art' and iterated.", kind: "build", feature: "ticket-badge" },
  { id: "teebot-email", file: "screens/teebot-email.png", t: "05:21:00", wall: "4:28 PM", title: "Tee Bot opens the email channel", caption: "Promo emails for the merch line, best-seller banners in, generic roundup formats deliberately out.", kind: "build", feature: "email-channel" },
  { id: "maturity-curve", file: "screens/maturity-curve.png", t: "05:26:00", wall: "4:33 PM", title: "The AI Maturity Curve", caption: "The keynote's framing chart: ask (chatbots) → do a task (copilots) → automate a job (a bot) → staff a function (a team of bots). xAI's product sits on the top rung.", kind: "session" },
  { id: "why-grokbot", file: "screens/why-grokbot.png", t: "05:30:00", wall: "4:37 PM", title: "'Why Grok Bot': the five pillars", caption: "Easy as iMessage · always-on 24/7 · uses your tools like you (computer use with your logins) · finishes the work · shareable templates.", kind: "session" },
  { id: "optimizing-costs", file: "screens/optimizing-costs.png", t: "05:43:00", wall: "4:50 PM", title: "Optimizing Costs — with 1M views watching", caption: "The honesty slide: what browser-using agents actually cost to run, shown while the broadcast crossed one million views.", kind: "session" },
  { id: "seo-workorder", file: "screens/seo-workorder.png", t: "05:48:00", wall: "4:55 PM", title: "The SEO work order", caption: "A bot-written growth plan with keyword targets, page fixes, and a dated execution timeline — shipped as a work order, not a report.", kind: "build", feature: "seo-work-order" },
  { id: "closing-guest", file: "screens/closing-guest.png", t: "08:17:00", wall: "5:24 PM", title: "Closing guest interview", caption: "The day's final segment: a remote guest with the build trio, before the stream closed at 1.1M views.", kind: "stage" },

  /* ── Day 2 — Wed Sep 16 ── */
  { id: "d2-opening", file: "screens/d2-opening.png", t: "live open", wall: "8:30 AM", day: 2, title: "Day 2 hold screen — the sales track begins", caption: "New broadcast, same studio: the fleet's second day opens with the question of the day — can it sell what it built?", kind: "stage" },
  { id: "d2-se-usecases", file: "screens/d2-whiteboard.png", t: "00:40:00 (Day 2 replay)", wall: "9:10 AM", day: 2, title: "Sales Engineer use cases: four quadrants", caption: "The SE session's use-case slide: Engineer (a technical resource drafted in seconds), Customer Expert (knows Codebricks and PlayerScale, flags unusual usage and power users), Echo (updates the deck live during calls; Granola/Gong follow-up), and Competitive Intel (uses competitor products, keeps battlecards current).", kind: "session" },
  { id: "d2-vision-deck", file: "screens/d2-vision-deck.png", t: "00:59:00 (Day 2 replay)", wall: "9:29 AM", day: 2, title: "Amrita's vision deck, assembled on screen", caption: "A Google Slides window titled as Amrita's vision deck, on screen during the Sales Engineering session. Her point about bot-built decks, on air: it cost her $20–30 versus four or five hours by hand.", kind: "session" },
  { id: "d2-se-bots", file: "screens/d2-se-bots.png", t: "01:03:00 (Day 2 replay)", wall: "9:33 AM", day: 2, title: "Two bots work one customer request together", caption: "The Sales Engineering session's demo chat: two agents trade messages to move a customer request forward, each doing its half of the job.", kind: "session" },
  { id: "d2-prototype", file: "screens/d2-prototype.png", t: "01:35:00 (Day 2 replay)", wall: "10:05 AM", day: 2, title: "The first playable draft: 'NodeBots BTB'", caption: "Two rows of three drafted bots face off, each card carrying its rarity tier, with a WIN stamp and a replay button below the board.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-game-docs", file: "screens/d2-game-docs.png", t: "01:50:00 (Day 2 replay)", wall: "10:20 AM", day: 2, title: "The game documentation, written down", caption: "The design lands in Notion: rosters, matches and replays, an Elo rating that starts every account at 1000, and the rarity draw from 90% common down to 0.9% epic.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-battle-whiteboard", file: "screens/d2-battle-whiteboard.png", t: "03:13:00 (Day 2 replay)", wall: "11:43 AM", day: 2, title: "Matchup screens, wireframed live", caption: "The matchup flow takes shape on the shared drawing canvas — a player's card wired to Dr. Eggbot on one side and a random draw on the other.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-design-brief", file: "screens/d2-design-brief.png", t: "03:27:00 (Day 2 replay)", wall: "11:57 AM", day: 2, title: "The Chief of Staff drafts the design brief", caption: "One of the specialist bots writes the game's design brief in the workspace while the build continues around it.", kind: "build" },
  { id: "d2-bot-workspace", file: "screens/d2-bot-workspace.png", t: "03:34:00 (Day 2 replay)", wall: "12:04 PM", day: 2, title: "Choosing an animation framework, delegated", caption: "The Chief of Staff surveys front-end animation options and reports back — one of several bot tasks running in parallel at midday.", kind: "build" },
  { id: "d2-echo", file: "screens/d2-echo.png", t: "03:50:00 (Day 2 replay)", wall: "12:20 PM", day: 2, title: "Echo tries its voice lines", caption: "Echo, an announcer bot for the game, tests its play-by-play lines in the chat.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-team-builder", file: "screens/d2-team-builder.png", t: "03:54:00 (Day 2 replay)", wall: "12:24 PM", day: 2, title: "The team builder, working", caption: "Pick a captain, reroll or confirm the roster — and the account bar already reads a Diamond rating of 1585.", kind: "build", feature: "cupcake-prototype" },
  { id: "d2-ads", file: "screens/d2-ads.png", t: "05:40:00 (Day 2 replay)", wall: "2:10 PM", day: 2, title: "The ad copy pass", caption: "The marketing bot drafts numbered ad and landing-page copy for the launch push.", kind: "build", feature: "ads-pipeline" },
  { id: "d2-offer", file: "screens/d2-offer.png", t: "07:30:00 (Day 2 replay)", wall: "4:00 PM", day: 2, title: "The on-stream offer", caption: "The event's own promo slide: a free month of Grok Bot for the first 1,000 users who duplicate Dr. Eggbot's template, QR code and all.", kind: "stage" },
  { id: "d2-close", file: "screens/d2-close.png", t: "08:22:30 (Day 2 replay)", wall: "4:52 PM", day: 2, title: "Day 2 signs off", caption: "The closing slate sets up the finale: 'Final day starts tomorrow at 8:30am PST.' The broadcast ended at 4:53 PM PT at 374.9K views.", kind: "stage" },

  /* ── Day 3 — Thu Sep 17 ── */
  { id: "d3-revops-usecases", file: "screens/d3-revops-usecases.png", t: "00:37:30 (Day 3 replay)", wall: "9:07 AM", day: 3, title: "RevOps & MarOps use cases: the six-card map", caption: "Marketing Operations opened on six plays: a self-completing to-do list, tools not just rules, the marketing–sales handoff, self-serve GTM data, territory planning, and a one-time CRM cleanup.", kind: "session" },
  { id: "d3-territory-planner", file: "screens/d3-territory-planner.png", t: "00:40:00 (Day 3 replay)", wall: "9:10 AM", day: 3, title: "Territory Planner referees an account dispute", caption: "A 'Territory Planner' bot drafted the stakeholder email and filed a Path task: two AEs claimed the same account; a territory-map sync Tuesday and a written ruling by Friday — with Approve / Hold buttons waiting on a human.", kind: "session" },
  { id: "d3-juno-lead-app", file: "screens/d3-juno-lead-app.png", t: "00:45:00 (Day 3 replay)", wall: "9:15 AM", day: 3, title: "Juno turns one line into a lead-review app spec", caption: "'A GTM product bot' named Juno took 'build an internal app for sales reps to review leads' and specced a swipe interface — left rejects with a reason, right accepts into a follow-up sequence — flagging auth as a day-one requirement.", kind: "session" },
  { id: "d3-starbase-contest", file: "screens/d3-starbase-contest.png", t: "01:10:00 (Day 3 replay)", wall: "9:40 AM", day: 3, title: "The Starbase challenge, step by step", caption: "The viewer contest slide: quote the challenge post, explain what your Bot does, link your shared Bot template, follow @Grok and @Bot — the prize is a trip to Starbase, entries through Sept 29.", kind: "stage" },
  { id: "d3-sake-game-stats", file: "screens/d3-sake-game-stats.png", t: "live", wall: "10:40 AM", day: 3, title: "A stats bot reads live match data", caption: "The studio block's build screen: a 'Launch dashboard — Session 1' card stamped 10:54 AM PT with a bug list (two fixed, two open), and Sake — a stats bot — pulling win-rate and difficulty signals from live match data to validate the game engine. The day's agenda sits beside it: Build: A Game Studio blocks around Grok Bot for Customer Success and Grok Bot for Marketing.", kind: "build" }
];
