/* ============================================================================
   GROK BOT GALAXY LIVE — WORKFLOW DATA (Days 1–3, transcript-verified)
   ----------------------------------------------------------------------------
   The division of labor: what the THREE HUMANS did versus what the AI
   EMPLOYEES did, on one time axis, with the deliverables that materialized.

   Loaded by the tracker AFTER data.js and products.js. Schema:

   window.GG_WORKFLOW = {
     lanes   : ["human", "ai"],
     steps   : [{ t, lane, actor, act, detail, deliverable, day }]  — chronological;
               t = Pacific wall time; deliverable = id in `deliverables` when
               this step produced one.
     deliverables : [{ id, t, name, status, detail, day }]
     stats   : small counts for the summary strip
   }

   Session-demo artifacts (the Flylo demo airline and its sample venue data,
   Mimi/Sherlock/Serena, Olive, the four-bot support org) are deliberately
   EXCLUDED — this tracks only the trio's actual build. Day 1 times are
   replay/visual reads; Day 2 and Day 3 times follow the broadcast clock
   (stream time from the 8:30 AM PT start).
   ============================================================================ */

window.GG_WORKFLOW = {
  lanes: ["human", "ai"],

  steps: [
    /* ── Day 1 — Tue Sep 15: the pop-up ── */
    { t: "8:40 AM",  lane: "human", actor: "Lauren · Roshan · Matt", act: "Opened the stream with no idea", detail: "Set the mission — build a company in three days — and admitted on air they had not chosen what to build. Announced the viewer contest (Starship-launch trip, ends Sep 29).", day: 1 },
    { t: "9:00 AM",  lane: "ai", actor: "Grok Bot platform", act: "Ran the 101 teaching block", detail: "The block covered bot onboarding, the bot Marketplace with installable community bots, and an email demo — a coffee-survey digest the bot writes and sends itself.", day: 1 },
    { t: "10:05 AM", lane: "human", actor: "Matt", act: "Took Peter Yang's distribution advice", detail: "Peter Yang, on air: 'anyone can build anything now… hard to make money from pure software… people pay for the hard stuff.' Distribution over software became the frame for every later choice.", day: 1 },
    { t: "10:15 AM", lane: "ai", actor: "grokbot", act: "Proposed company concepts", detail: "Returned candidate directions with pricing-tier sketches and a business-plan checklist (marketing, sales, ops, finance, legal, engineering).", day: 1 },
    { t: "10:50 AM", lane: "human", actor: "Lauren · Roshan · Matt", act: "Chose a restaurant pop-up, for now", detail: "On air they landed on 'pop-up OS for restaurants' — a real SF pop-up with a partnering chef, ticketed as an experiential dinner, ops software as the meta product. First deliverable of the day.", day: 1, deliverable: "idea" },
    { t: "10:55 AM", lane: "ai", actor: "grokbot", act: "Produced the full business plan", detail: "The plan covered product, pricing tiers, marketing strategy and objectives, with a scoping checklist across departments.", day: 1 },
    { t: "11:25 AM", lane: "human", actor: "Matt", act: "Absorbed Codie Sanchez's distribution doctrine", detail: "Her advice, on air: sell to three people first; distribution is the moat; controversy marketing (2.4M and 5.7M-view examples); keep a proof vault; oversee bots intensely.", day: 1 },
    { t: "11:45 AM", lane: "human", actor: "Matt · Codie", act: "Created an operator-research bot together, on air", detail: "Turned her advice into prompts — 'top San Francisco restaurant tours.' A human decision shipped as a bot within minutes.", day: 1, deliverable: "operator-bot" },
    { t: "12:30 PM", lane: "ai", actor: "engineering bots", act: "Ran the multi-agent pipeline demo", detail: "During the Engineering session the loop ran a finished PR, a Sage deploy with logs, a review queue, a designer agent on merch art, and a legal-docs agent In Queue.", day: 1, deliverable: "pipeline" },
    { t: "1:00 PM",  lane: "human", actor: "Lauren", act: "Set the engineering rules — and watched them break", detail: "On air, after steve opened a pull request: 'New rule: no pull requests. We ship to main… until somebody yells at me.'", day: 1 },
    { t: "1:05 PM",  lane: "ai", actor: "steve · tater · hashbrown", act: "Pushed a ~2,000-line PR; built the reviewer", detail: "steve's ~2,000-line PR broke the brand-new rule, showing why bot staff need oversight. tater posted PR #10 to for-review via cursor.com/agents; hashbrown was created to review tater's PRs.", day: 1 },
    { t: "2:06 PM",  lane: "human", actor: "Roshan · Matt", act: "Debugged a stuck cloud agent with steve", detail: "'Is it actually moving or just sitting there?' The diagnosis was a subagent, 'still chasing the PR, not the spinner.' Humans and bots worked the same debugging thread.", day: 1 },
    { t: "2:07 PM",  lane: "ai", actor: "grokbot", act: "Wrote the event-builder spec", detail: "'User should be able to create their own event — events have a date/time, sessions, venue, staff.' The core product sentence of the pop-up track, authored by an agent (on screen).", day: 1 },
    { t: "2:46 PM",  lane: "human", actor: "PM session (Kevin Niparko + Roshan)", act: "Ran the Product Managers session", detail: "The 'Why many agents' slide made the case on referencability, scoped memory and parallelism — 'not one omniscient bot, but a full roster of teammates' — with the demo chat running on the session's own sample venue data, Fly Low Airlines.", day: 1 },
    { t: "3:25 PM",  lane: "human", actor: "the trio + guest Eric", act: "Let the idea drift toward a Grok Bot pop-up", detail: "On air, 'we're going to try and start a grok pop-up' — merch, venue, ticketing; platform demoted to a stretch goal; 100–200 guests, Oct 15 floated. At close: 'we might still be shifting.'", day: 1 },
    { t: "3:55 PM",  lane: "ai", actor: "the fleet", act: "Grew to 26 bots and retired 10", detail: "Ops chat showed QA picking up PRs and a Darcy-bot redeploy.", day: 1 },
    { t: "4:00 PM",  lane: "human", actor: "Founders (Shub Gaur)", act: "Ran the Founders session", detail: "The AI Maturity Curve and the five-pillar 'Why Grok Bot' grid framed the product for one-person companies, a bot-prepared sales-call brief ran on clearly-labeled example data, and the hosts aired the platform's own cost math as the view counter crossed one million.", day: 1 },
    { t: "4:19 PM",  lane: "ai", actor: "Tee Bot · Pixel", act: "Designed pop-up supplies and merch", detail: "On screen were ticket stubs with tier badges, lanyards, and plush concepts — the plush line iterated 'against the official art.'", day: 1, deliverable: "tickets" },
    { t: "4:20 PM",  lane: "ai", actor: "dr. eggbot", act: "Stood up the lander", detail: "The domain was live on Vercel, wired to PlanetScale — 'the domain is live… I hooked it up to our database' — with viewers told 'don't submit yet… throwaway prototype.' The URL (shipbythursday.day) was spoken on air.", day: 1, deliverable: "lander" },
    { t: "4:25 PM",  lane: "ai", actor: "grokbot", act: "Filed the SEO work order", detail: "The order specified a keyword plan, page-weight cuts, a trimmed form and an FAQ, with a dated execution timeline (on screen).", day: 1, deliverable: "seo" },
    { t: "4:28 PM",  lane: "ai", actor: "Tee Bot", act: "Opened the email channel", detail: "On screen, promo emails were drafted and sent for the merch line, carrying best-seller banners and skipping generic roundups.", day: 1, deliverable: "email" },
    { t: "5:00 PM",  lane: "human", actor: "the trio + guest Jenny", act: "Reshaped the pop-up with an event producer's help", detail: "Jenny's 22-bot event-production suite (venue scout, permits, budgets, invite lists) reframed the plan in the final hour; overnight agents commissioned — budget bot, venue-scout outreach, invite-list sourcing.", day: 1 },
    { t: "5:30 PM",  lane: "human", actor: "all three", act: "Wrapped Day 1 at ~5:30 PM, 1.1M views", detail: "'We're going to wrap it at 5:30' — off the air close to it after ~8h 45m. The counter read 1.1M; the hosts had shown their own agent cost math ('browser use is super powerful… also expensive') as it crossed 1M.", day: 1 },

    /* ── Day 2 — Wed Sep 16: the 'Cupcake' demo becomes the build ── */
    { t: "8:30 AM",  lane: "human", actor: "Lauren · Roshan · Matt", act: "Opened Day 2 by planning the build out loud", detail: "'Lauren, do you want to take us through some of the thoughts on how we could MVP this?' Her answer: a rough plan built with her P-Stack planning playbook — checklists, pseudo-code, data structures.", day: 2 },
    { t: "8:31 AM",  lane: "human", actor: "Sales Engineering (Amrita, Cursor)", act: "Ran the SE session on the Flylo demo app", detail: "'My name is Amrita. I am a field engineer here at Cursor.' Mimi (case-study slides), Sherlock (repo expert that spawned three more bots live), Serena (competitive intel) — on xAI's own demo airline. On air: Grok Bot runs Grok 4.6; VMs are Linux-only; her bot-built deck cost $20–30 vs 4–5 hours.", day: 2 },
    { t: "9:25 AM",  lane: "human", actor: "Matt (Lauren offline)", act: "Took the wheel for the build block", detail: "Lauren's machine went offline; Matt drove with her as 'backseat driver' — 'if you have dr. eggbot installed, you have an engineer bot.'", day: 2 },
    { t: "9:27 AM",  lane: "human", actor: "Matt", act: "Named the game as the goal", detail: "'Hey, take a look at that document. That's going to be our game. Our first goal is to make a landing page.'", day: 2 },
    { t: "9:31 AM",  lane: "ai", actor: "grokbot · growth engineer bot", act: "Spun up the landing page", detail: "'We have our lander getting spun up' — scaffold built in parallel with the design argument, under the rule 'subtract before you add… removing auth, removing a waitlist.'", day: 2, deliverable: "thursday-lander" },
    { t: "9:32 AM",  lane: "ai", actor: "Steve · dr. eggbot · Creative Director", act: "Staffed the org on demand", detail: "Steve holds the project context as chief of staff; dr. eggbot told to 'create an engineering bot… use P-Stack and Potato Mode to spawn cloud agents… orchestrate these cloud agents and supervise them and check their work'; the creative-director bot researched game visuals ('a total noob to video games') into a slider-tunable SVG asset playground.", day: 2, deliverable: "asset-sliders" },
    { t: "9:36 AM",  lane: "human", actor: "Lauren · Matt", act: "Set the game's tuning principles", detail: "The charisma-vs-dexterity counter ('rock paper scissors… the bonus being 20% if you can tweak that on the fly and just replay'), debug sliders in the UI, and the north star: 'we need to shorten the time to fun.'", day: 2 },
    { t: "9:39 AM",  lane: "ai", actor: "Knowledge Base bot", act: "Rewrote the company doc around the game demo", detail: "'Our knowledge base bot… started working on updating our Notion with our company doc. So now we're working on our game design studio… we're documenting the pivot and eventually what our go-to-market strategy might be.' On screen: 'There is no pop-up' — the October event tracks were retired, and the build's center of gravity moved to the game for good.", day: 2, deliverable: "pivot-doc" },
    { t: "9:50 AM",  lane: "ai", actor: "engineering bots", act: "Set the prototype's rules: no login, no database", detail: "The prototype skipped sign-in and a database ('we don't need login yet when we don't even know if the game is fun') and ran vanilla HTML/CSS/JS, three UI variants, marketplace bots as seed data, debug panels with sliders.", day: 2, deliverable: "cupcake-proto" },
    { t: "10:03 AM", lane: "human", actor: "Matt", act: "Played the first draft and broke it", detail: "'I'm gonna of course pick Dr. Eggbot… we have three common bots.' Caught the stat-total bug live; approved the debug panel ('tune the advantage'); decided matches resolve instantly with animation on top.", day: 2 },
    { t: "10:42 AM", lane: "ai", actor: "customer story (Icon Coffee)", act: "Showed Icon Coffee's bot in daily use", detail: "Marcel, co-owner of Icon Coffee (SF): his bot Rex triages school email, reads the POS via API for metrics, and optimized the menu from a photo — 'an extra hour, two hours in my day.'", day: 2 },
    { t: "11:09 AM", lane: "human", actor: "guest Karen (X) Cheng", act: "Showed how creators use bots daily", detail: "A morning-newspaper bot (newspaper.karenx.com) that finds printers on Wi-Fi; a Vestaboard package tracker. Her feature request — better VM login lifecycle — matched the fleet's own complaint: 'things are always getting logged out on the virtual machine.'", day: 2 },
    { t: "11:41 AM", lane: "human", actor: "Lauren · Roshan · Matt", act: "Whiteboarded the battle screen", detail: "The flow ran captain first, then the team, then order, then match; tiers hide raw ELO ('instead of saying my elo is 1372, I'm diamond'); 'maybe this is fine. We'll ship it'; 'no time for PRs'; 2D before 3D.", day: 2 },
    { t: "12:16 PM", lane: "ai", actor: "Cupcake Eng · image-gen bot", act: "Gave the game its code name and icons", detail: "'We may need to start thinking of a name… It's just a code name.' A cupcake logo designed; ability icons generated and cleaned with background removal. 'Cupcake' had first been spoken at 11:58 ('who's the best cupcake battler').", day: 2 },
    { t: "12:29 PM", lane: "human", actor: "Sales (Chris Dillettes & Mark Wright)", act: "Ran the Sales session", detail: "Echo updated the deck live mid-call from Granola (~2 minutes); Olive prepped meetings and drafted replies; Salesforce auto-updated from call notes; the PG agent pulled personal hooks from X posts; a growth bot matched the user's writing voice — all on the Flylo sample data.", day: 2 },
    { t: "12:35 PM", lane: "human", actor: "the trio", act: "Made the pivot the stream's public identity", detail: "The broadcast retitled itself 'Grok Bot builds a Game Studio LIVE' — 'we're a game studio building a game along a three-day journey,' on air — while the ops-software line stayed in the plan doc, heading for Thursday.", day: 2 },
    { t: "1:13 PM",  lane: "human", actor: "guest Matt Berman + intern Shardul", act: "Showed the agent life outside xAI", detail: "Berman's examples were a family bot, marketplace sales with auto-negotiation, and $1,000/yr off PG&E. Shardul Marathe ('first forward-deployed intern'): recruiter-finder, alumni-directory email finder, cover-letter critic.", day: 2 },
    { t: "2:05 PM",  lane: "ai", actor: "chief of staff · dr. eggbot · remotion ads bot", act: "Built the ad pipeline", detail: "They onboarded 'a remotion ads bot for a Cupcake', which wrote ~6,000 lines across 12 files into 9:16 and 16:9 spots for LinkedIn, Instagram and X, with a localhost conflict debugged on air.", day: 2, deliverable: "ads-pipeline" },
    { t: "2:30 PM",  lane: "human", actor: "SDRs (Simon)", act: "Ran the SDR session", detail: "The 'Simon soldiers' are a sub-agent army working a 50-prospects-a-day routine, demoed on the Flylo account — the SDR's job becomes editing bot drafts.", day: 2 },
    { t: "3:10 PM",  lane: "ai", actor: "Cupcake Eng · founding engineer bot · glow 3d", act: "Went scrappy — backend, kanban, 3D experiments", detail: "The bots split client and server ('you can just modify the client and cheat'), built the 'cupcake board' kanban ('our own little ticketing system'), assigned auth (Clerk), ran a 3D prototyping swarm via Potato Mode, and pushed the backend to Vercel — 'delete all the tests… true scrappy mode.' A coordinator agent in Cursor Projects even said 'mashed' for merge.", day: 2 },
    { t: "4:00 PM",  lane: "human", actor: "Customer Support (David)", act: "Ran the Support session", detail: "The four-bot support org (build/reply/alert/tune) ran on Plain, Notion, Supabase and Stripe over Flylo's $20/month wifi: a password reset cited the doc, an SSO question hit no docs and was handed off at low confidence, and refunds were granted or denied by the 14-day policy without leaking it. The economics stated on air were $1–2 per medium ticket and about $0.20 scripted.", day: 2 },
    { t: "4:41 PM",  lane: "human", actor: "all three", act: "Set the deadline and signed off", detail: "'72-hour live stream here where we ship a product by Thursday.' Final state: X login works, leaderboard wired but empty, ratings placeholder, 'there's a bug. So I can't actually add any bots yet.' Day 3: deploy, rename, play with chat, 'make it go viral — we have one day to grow our business.'", day: 2 },

    /* ── Day 3 — Thu Sep 17: ship day — the build launches as Thursday Arena ── */
    { t: "8:30 AM",  lane: "human", actor: "Lauren · Roshan · Matt", act: "Opened ship day under a launching-today banner", detail: "The final broadcast went live at 8:30 AM PT titled 'Building a company in 3 days — launching today!', with the fleet returning to a demo that had been one bug short of matches the previous evening.", day: 3 },
    { t: "9:00 AM",  lane: "human", actor: "Marketing Ops (Matthew Silberman & Teresa Hsu)", act: "Ran the Marketing Operations session", detail: "Six RevOps & MarOps plays — a self-completing to-do list, tools not just rules, the marketing–sales handoff, self-serve GTM data, territory planning, a one-time CRM cleanup — then two demos in ten minutes: a Territory Planner bot that filed an AE account dispute as a task with Approve/Hold buttons, and Juno, a GTM product bot, that turned one line of intent into a lead-review app spec. The viewer contest's entry steps went on screen at 9:40.", day: 3 },
    { t: "10:40 AM", lane: "ai", actor: "Sake", act: "Validated the game engine from live match data", detail: "A 'Launch dashboard — Session 1' card carried a bug list (two fixed, two open) while Sake, a stats bot, pulled win-rate and difficulty signals from live match data to validate the game engine.", day: 3 },
    { t: "10:46 AM", lane: "ai", actor: "integrations bot", act: "Wired the stack and published the kill-list", detail: "One message reported the connections — GitHub with two repos, Slack with three channels, Notion with four databases, Linear with two projects, Vercel and Postgres, plus webhooks — alongside a 'sudden-death feature kill-list' for the ship cut-line, signed 'Ship by Thursday.' The fleet widget read 43 online.", day: 3 },
    { t: "10:52 AM", lane: "human", actor: "the trio + chat", act: "Played the first live match with the audience", detail: "The hosts kept one of Wednesday's sign-off promises, playing matches live with chat, and the result screen showed 'You took round 1' with a Play Again button. The cards carried player pets and a dice-roll RNG mechanic; several still read 'no image provided' while an Image Gen bot sat active in the roster.", day: 3 },
    { t: "10:58 AM", lane: "human", actor: "the trio", act: "Named the build and shipped it: THURSDAY ARENA", detail: "The rename-and-deploy promise was kept on schedule: a deployed front page went on screen under the final name — a player profile at a 1000 rating, a Play button, a 'priority queue: eng' banner, and Leaderboard / Your matches / Tips / Read handbook panels — beside a deploy diff in the editor. The public URL sat in the address bar but was not yet legible on stream.", day: 3, deliverable: "arena-launch" },
    { t: "11:19 AM", lane: "ai", actor: "the fleet", act: "Opened the in-game shop", detail: "The build grew a shop whose three cards, each priced at 3G, were go-to-market jokes — including a hiring-signals tracker whose sales pitch was 'snipes the hire you just missed.'", day: 3, deliverable: "shop" },
    { t: "11:30 AM", lane: "ai", actor: "the fleet", act: "Measured its own funnel", detail: "A 'Funnel snapshot' dashboard tracking practice, convert and play on the studio screen: 2,255 practice sessions opened, 742 completed, 268 converted, 193 account creations, and 2,983 public matches. Whether the numbers reflect public traffic or seeded test data was not stated on screen.", day: 3, deliverable: "analytics" },
    { t: "12:04 PM", lane: "ai", actor: "the fleet", act: "Stood up marketing operations from the Marketplace", detail: "The studio block's new thread was captioned 'Standing up marketing operations,' and the screen showed a Marketplace listing for 'Cerebro' by Marinos — a community-built GTM bot with duplicate and download buttons. Installing a specialist template and then teaching it the house rules was the fastest way to staff a function, demonstrated on the company's own build.", day: 3 },
    { t: "12:30 PM", lane: "human", actor: "Blake Schuller", act: "Ran the Post-Sales session", detail: "The Marketplace-assembled team and 'Gus', a chief-of-staff bot, ran status digests, scheduled routines and a self-improvement scan — session-demo data on the Flylo environment, not the trio's build.", day: 3 },
    { t: "1:19 PM",  lane: "ai", actor: "the deployed build", act: "Answered to its own URL on screen", detail: "thursdayarena.com became legible on stream and live — the wordmark, a Play button and the roster's character cards on the deployed site — with check-agents sent to reproduce a shop-button bug on the live public pages.", day: 3 },
    { t: "2:06 PM",  lane: "ai", actor: "the deployed build", act: "Ran a ticker of player posts on its own landing page", detail: "The landing page's live ticker scrolled X posts from players showing off the teams they had built, with a signed-in player profile carrying paired Elo ratings beside the character cards — the 'make it go viral' loop of play, post and pull others in, wired into the site itself.", day: 3 },
    { t: "2:14 PM",  lane: "ai", actor: "the fleet", act: "Edited how its own backlog runs", detail: "A triage thread changed the backlog's process — one report per site while conflicts last, a team attribute on every ticket, consolidated deploys — and a bot shared its own work to the team with View PR and Open in Cursor buttons, next to a drift-flagged do-not-merge item.", day: 3 },
    { t: "2:30 PM",  lane: "human", actor: "Josh Kim", act: "Ran the Marketing session", detail: "The final teaching block of the broadcast, 2:30–4:00 PM: a Market Researcher bot briefed in one message handed off to a Product Marketer that committed a positioning brief to the shared workspace, and a Website Ops bot took a three-step order for the landing page.", day: 3 },
    { t: "3:03 PM",  lane: "human", actor: "Josh Kim", act: "Closed the Marketing session with three lessons", detail: "The 'What we learned' slide ran three lines: scope bots like a job description, then trust them with the tools, access and context a teammate would get, then invest in them the way you would a person — and copy from the marketplace's shared templates.", day: 3 },
    { t: "3:15 PM",  lane: "human", actor: "the trio", act: "Ran the final showcase and signed off", detail: "The closing segment opened on the game's own dashboard — 4,898 public matches, 4,500 practice sessions, a 47.6% win rate, 677 concurrent players — stated the official rules coached by dr. eggbot, and ended with the hosts mid-ranked-match against a viewer at the 4:28 PM close (173.4K viewers, 7h 58m).", day: 3, deliverable: "showcase" },
    { t: "3:50 PM",  lane: "ai", actor: "the fleet", act: "Filed a pull request with its own test evidence", detail: "GitHub pull request #274, a leaderboard fix written by the fleet, carried a description of what changed and what was deliberately left alone, a Tests section running the suite, and the verdict line 'All green' — the 'delete all the tests' call of Day 2 had grown into bots that attach test evidence to their work.", day: 3, deliverable: "pr-274" },
    { t: "4:15 PM",  lane: "ai", actor: "the fleet", act: "Charted the day's traffic in five-minute waves", detail: "The showcase's traffic chart, stamped 4:15 PM PT, showed practice starts and X signups rising in waves across the whole broadcast day, each wave traceable to something the stream had just done on air.", day: 3 }
  ],

  deliverables: [
    /* ── Day 1 ── */
    { id: "idea",    t: "10:50 AM", name: "The 'Pop-up OS' concept and business plan", status: "SHIPPED", detail: "Restaurant pop-up with partnering chef and venue; ops software as the meta product. Named the company: Ship by Thursday.", day: 1 },
    { id: "operator-bot", t: "11:45 AM", name: "Operator-research bot (built live with Codie Sanchez)", status: "SHIPPED", detail: "Research prompts seeded with the guest's distribution doctrine — 'top San Francisco restaurant tours.'", day: 1 },
    { id: "pipeline", t: "12:30 PM", name: "Multi-agent engineering pipeline", status: "SHIPPED", detail: "The loop ran tater's pull request through a Sage deploy with logs and a review queue, with designer and legal-docs agents attached, via Cursor Cloud Agents.", day: 1 },
    { id: "lander",  t: "4:20 PM",  name: "Domain + live lander (shipbythursday.day)", status: "STAGING", detail: "Live on Vercel wired to PlanetScale — the URL spoken on air, viewers told 'don't submit yet… throwaway prototype.'", day: 1 },
    { id: "tickets", t: "4:19 PM",  name: "Ticket stubs, badges and plush concepts", status: "SHIPPED", detail: "Stub designs with tier badges and lanyards on the canvas (screen); the plush concepts iterated on air. The work stopped at designs, with no checkout built.", day: 1 },
    { id: "email",   t: "4:28 PM",  name: "Email marketing channel", status: "SHIPPED", detail: "The merch email thread: promo drafts with best-seller banners and no generic roundups (screen).", day: 1 },
    { id: "seo",     t: "4:25 PM",  name: "SEO work order with dated execution plan", status: "SHIPPED", detail: "Keyword plan, page-weight and form fixes, FAQ — execution timeline dated through Thursday (on screen).", day: 1 },

    /* ── Day 2 ── */
    { id: "thursday-lander", t: "9:31 AM", name: "The game's landing page (V1)", status: "SHIPPED", detail: "'Our first goal is to make a landing page' — scaffolded the same hour with auth and waitlist deliberately removed, and deployed on launch day as the build's own front page.", day: 2 },
    { id: "asset-sliders", t: "9:32 AM", name: "SVG asset playground (visual prototyping)", status: "SHIPPED", detail: "The creative-director bot built slider-tunable flat-SVG tokens, run locally, so looks could be iterated before code.", day: 2 },
    { id: "pivot-doc", t: "9:39 AM", name: "Company doc rewritten around the game demo", status: "SHIPPED", detail: "'Now we're working on our game design studio… we're documenting the pivot.' The October pop-up event tracks were retired in Notion, and the build moved to the game.", day: 2 },
    { id: "cupcake-proto", t: "9:50 AM", name: "The 'Cupcake' prototype → Thursday Arena", status: "SHIPPED", detail: "It began as a constraints-first demo of prototyping speed — marketplace-bot draft battler, no login, no database, debug sliders — and became the company's build: first played 10:03 on Day 2, one bug short of matches at the close, then named, deployed and playing live matches as Thursday Arena on Day 3.", day: 2 },
    { id: "ads-pipeline", t: "2:05 PM", name: "Remotion ad pipeline (~6,000 lines)", status: "SHIPPED", detail: "Agent-written video ads in 9:16 and 16:9 for LinkedIn/Instagram/X; a stadium-billboard marketplace sketched for Day 3.", day: 2 },

    /* ── Day 3 ── */
    { id: "arena-launch", t: "10:58 AM", name: "THURSDAY ARENA — the build, named and deployed", status: "SHIPPED", detail: "The final name went on a deployed front page with a Play button and a live leaderboard of named players — the code-named 'Cupcake' demo launched as the company's product on ship day, with 2,983 public matches on the board by 11:30 AM PT.", day: 3 },
    { id: "shop", t: "11:19 AM", name: "The in-game shop", status: "SHIPPED", detail: "Three cards on the shelf at 3 gold each, every one a go-to-market joke — the auto-battler grew an economy whose items poke fun at the sales world.", day: 3 },
    { id: "analytics", t: "11:30 AM", name: "Launch-day funnel dashboard", status: "SHIPPED", detail: "The build tracked its own funnel, with practice sessions, conversions, account creations and public matches on one screen.", day: 3 },
    { id: "showcase", t: "3:15 PM", name: "The final showcase: the numbers, then a match against a viewer", status: "SHIPPED", detail: "The closing segment opened on the game's own dashboard — 4,898 public matches, 4,500 practice sessions, a 47.6% win rate, 677 concurrent players — and the hosts signed off at the 4:28 PM PT close mid-ranked-match against a viewer.", day: 3 },
    { id: "pr-274", t: "3:50 PM", name: "Bot-authored pull request #274, with its own tests", status: "SHIPPED", detail: "A leaderboard fix written by the fleet, carrying its own test report and an 'All green' verdict while the hosts played the closing match.", day: 3 }
  ],

  stats: {
    humanMoves: 34,
    aiMoves: 29,
    deliverables: 17,
    note: "Humans chose, ruled, tuned, debugged and approved. Bots proposed, produced, deployed and iterated. Every deliverable needed at least one of each."
  },

  footnote: "Session-demo artifacts (the Flylo demo airline and its sample venue data, Mimi/Sherlock/Serena, Olive, the four-bot support org) are excluded: that data belonged to the teaching demos, not the trio's build."
};
